-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(B.AMOUNT) * A.PRICE as TOTAL_SALES
from FOOD_PRODUCT as A JOIN FOOD_ORDER as B ON A.PRODUCT_ID = B.PRODUCT_ID
where YEAR(B.PRODUCE_DATE) = 2022 and MONTH(B.PRODUCE_DATE) = 5
group by PRODUCT_ID, PRODUCT_NAME
order by TOTAL_SALES desc, A.PRODUCT_ID;
