-- 코드를 작성해주세요
SELECT SUB.TOTAL SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E JOIN (
    SELECT SUM(SCORE) TOTAL, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
) SUB ON E.EMP_NO = SUB.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;